// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg4CM8h9EEPqY8zygGJORGJIDcoOsE-2nOE',
    appId: '1:790343702945:web:1ebb2bd2978615e8ab53e0',
    messagingSenderId: '790343702945',
    projectId: 'stocky-3a009',
    authDomain: 'stocky-3a009.firebaseapp.com',
    storageBucket: 'stocky-3a009.appspot.com',
    measurementId: 'G-PKY4N8G3WF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAenxc0o23UPuXwYXDnzphUKAysCQTX1Tk',
    appId: '1:790343702945:android:a6481bc79474e75fab53e0',
    messagingSenderId: '790343702945',
    projectId: 'stocky-3a009',
    storageBucket: 'stocky-3a009.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOu4AtqoRnqTr6mKrqslTFNBfWSM4erpo',
    appId: '1:790343702945:ios:43cd12a8c1763de3ab53e0',
    messagingSenderId: '790343702945',
    projectId: 'stocky-3a009',
    storageBucket: 'stocky-3a009.appspot.com',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOu4AtqoRnqTr6mKrqslTFNBfWSM4erpo',
    appId: '1:790343702945:ios:a8d2b964bf98e518ab53e0',
    messagingSenderId: '790343702945',
    projectId: 'stocky-3a009',
    storageBucket: 'stocky-3a009.appspot.com',
    iosBundleId: 'com.example.project1.RunnerTests',
  );
}
